version: '3.8'

services:
  bot:
    image: python:3.11-slim
    container_name: bot-zenyx-local
    working_dir: /app
    command: >
      bash -c "
        pip install --no-cache-dir -r requirements.txt &&
        python main.py
      "
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - bot-local-network

  redis:
    image: redis:alpine
    container_name: redis-local
    restart: unless-stopped
    networks:
      - bot-local-network

networks:
  bot-local-network:
    driver: bridge